import { isPriorityCity } from "@/lib/seo/priorityMarkets";

/** Population in thousands for tiering (~top 200 U.S. cities). Key: `${stateSlug}/${citySlug}`. */
const CITY_POPULATION_K: Record<string, number> = {
  "new-york/new-york-city": 8336,
  "new-york/manhattan": 1694,
  "new-york/brooklyn": 2647,
  "new-york/queens": 2405,
  "new-york/the-bronx": 1472,
  "new-york/staten-island": 495,
  "california/los-angeles": 3898,
  "california/san-diego": 1387,
  "california/san-jose": 1013,
  "california/san-francisco": 873,
  "california/sacramento": 524,
  "california/oakland": 440,
  "california/irvine": 307,
  "california/anaheim": 345,
  "texas/houston": 2305,
  "texas/san-antonio": 1547,
  "texas/dallas": 1304,
  "texas/austin": 979,
  "texas/fort-worth": 919,
  "texas/el-paso": 678,
  "florida/jacksonville": 950,
  "florida/miami": 442,
  "florida/tampa": 384,
  "florida/orlando": 307,
  "florida/fort-lauderdale": 182,
  "florida/st-petersburg": 258,
  "illinois/chicago": 2746,
  "pennsylvania/philadelphia": 1584,
  "pennsylvania/pittsburgh": 303,
  "arizona/phoenix": 1608,
  "arizona/tucson": 543,
  "arizona/scottsdale": 241,
  "arizona/mesa": 504,
  "arizona/tempe": 180,
  "arizona/chandler": 275,
  "ohio/columbus": 905,
  "ohio/cleveland": 373,
  "ohio/cincinnati": 309,
  "north-carolina/charlotte": 874,
  "north-carolina/raleigh": 467,
  "north-carolina/durham": 283,
  "indiana/indianapolis": 887,
  "washington/seattle": 749,
  "washington/spokane": 228,
  "washington/tacoma": 219,
  "colorado/denver": 715,
  "colorado/colorado-springs": 478,
  "colorado/boulder": 108,
  "colorado/aurora": 386,
  "colorado/fort-collins": 169,
  "massachusetts/boston": 675,
  "massachusetts/cambridge": 118,
  "massachusetts/worcester": 206,
  "tennessee/nashville": 689,
  "tennessee/memphis": 633,
  "tennessee/knoxville": 190,
  "michigan/detroit": 639,
  "michigan/grand-rapids": 198,
  "michigan/ann-arbor": 123,
  "oregon/portland": 652,
  "oregon/eugene": 176,
  "oregon/salem": 175,
  "nevada/las-vegas": 641,
  "nevada/reno": 264,
  "nevada/henderson": 317,
  "maryland/baltimore": 585,
  "maryland/bethesda": 68,
  "maryland/rockville": 67,
  "wisconsin/milwaukee": 577,
  "wisconsin/madison": 269,
  "minnesota/minneapolis": 429,
  "minnesota/saint-paul": 311,
  "missouri/kansas-city": 508,
  "missouri/st-louis": 301,
  "louisiana/new-orleans": 383,
  "louisiana/baton-rouge": 227,
  "kentucky/louisville": 633,
  "kentucky/lexington": 322,
  "oklahoma/oklahoma-city": 681,
  "oklahoma/tulsa": 413,
  "connecticut/hartford": 121,
  "connecticut/new-haven": 134,
  "connecticut/stamford": 135,
  "connecticut/bridgeport": 148,
  "new-jersey/newark": 311,
  "new-jersey/jersey-city": 292,
  "new-jersey/hoboken": 58,
  "new-jersey/paterson": 159,
  "new-jersey/elizabeth": 137,
  "new-jersey/edison": 107,
  "new-jersey/trenton": 90,
  "new-jersey/princeton": 31,
  "georgia/atlanta": 498,
  "georgia/augusta": 202,
  "georgia/savannah": 147,
  "georgia/alpharetta": 66,
  "georgia/marietta": 61,
  "virginia/virginia-beach": 459,
  "virginia/norfolk": 238,
  "virginia/richmond": 226,
  "virginia/arlington": 238,
  "utah/salt-lake-city": 200,
  "utah/provo": 115,
  "iowa/des-moines": 214,
  "arkansas/little-rock": 202,
  "arkansas/fayetteville": 93,
  "arkansas/bentonville": 54,
  "alabama/birmingham": 200,
  "alabama/huntsville": 215,
  "alabama/mobile": 187,
  "south-carolina/charleston": 150,
  "south-carolina/columbia": 137,
  "south-carolina/greenville": 70,
  "nebraska/omaha": 486,
  "nebraska/lincoln": 291,
  "new-mexico/albuquerque": 564,
  "idaho/boise": 235,
  "montana/billings": 117,
  "montana/bozeman": 53,
  "hawaii/honolulu": 350,
  "alaska/anchorage": 291,
  "delaware/wilmington": 71,
  "rhode-island/providence": 190,
  "new-hampshire/manchester": 115,
  "maine/portland": 68,
  "west-virginia/charleston": 48,
  "south-dakota/sioux-falls": 192,
  "north-dakota/fargo": 125,
  "wyoming/cheyenne": 65,
  "vermont/burlington": 44,
};

export type CityTier = 1 | 2 | 3;

export function getCityPopulation(stateSlug: string, citySlug: string): number | undefined {
  return CITY_POPULATION_K[`${stateSlug}/${citySlug}`];
}

export function getCityTier(stateSlug: string, citySlug: string): CityTier {
  if (isPriorityCity(stateSlug, citySlug)) return 1;

  const popK = getCityPopulation(stateSlug, citySlug);
  if (popK !== undefined) {
    if (popK >= 400) return 1;
    if (popK >= 100) return 2;
    return 3;
  }

  return 3;
}

export function getCityTierLabel(tier: CityTier): string {
  if (tier === 1) return "major metro";
  if (tier === 2) return "mid-size market";
  return "local market";
}
