
context /services/web-development/ {
  type                    redirect
  uri                     /services/custom-website-development/
  allowBrowse             1
}

context /services/web-development {
  type                    redirect
  uri                     /services/custom-website-development/
  allowBrowse             1
}

context /services/app-development/ {
  type                    redirect
  uri                     /services/mobile-app-development/
  allowBrowse             1
}

context /services/app-development {
  type                    redirect
  uri                     /services/mobile-app-development/
  allowBrowse             1
}

context /services/digital-marketing/ {
  type                    redirect
  uri                     /services/digital-marketing-strategy/
  allowBrowse             1
}

context /services/digital-marketing {
  type                    redirect
  uri                     /services/digital-marketing-strategy/
  allowBrowse             1
}

context /services/ai-automations/ {
  type                    redirect
  uri                     /services/ai-chatbot-development/
  allowBrowse             1
}

context /services/ai-automations {
  type                    redirect
  uri                     /services/ai-chatbot-development/
  allowBrowse             1
}

context /services/saas-application-development/ {
  type                    redirect
  uri                     /services/saas-development/
  allowBrowse             1
}

context /services/saas-application-development {
  type                    redirect
  uri                     /services/saas-development/
  allowBrowse             1
}

context /services/cro-seo/ {
  type                    redirect
  uri                     /services/conversion-rate-optimization/
  allowBrowse             1
}

context /services/cro-seo {
  type                    redirect
  uri                     /services/conversion-rate-optimization/
  allowBrowse             1
}

context /services/e-commerce-development/ {
  type                    redirect
  uri                     /services/shopify-store-development/
  allowBrowse             1
}

context /services/e-commerce-development {
  type                    redirect
  uri                     /services/shopify-store-development/
  allowBrowse             1
}

context /services/ecommerce-development/ {
  type                    redirect
  uri                     /services/shopify-store-development/
  allowBrowse             1
}

context /services/ecommerce-development {
  type                    redirect
  uri                     /services/shopify-store-development/
  allowBrowse             1
}
